# Generated by Django 6.1.1 on 2026-09-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('edad', models.PositiveBigIntegerField()),
                ('carrera', models.CharField(choices=[('SOF', 'Software'), ('ADM', 'Administracion'), ('DER', 'Derecho'), ('OTR', 'Otra')], max_length=3)),
                ('comentarios', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
