# Generated by Django 6.1.1 on 2026-09-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
